@extends('layout')
@section('content')
@php($money = fn($minor) => number_format($minor / 100, 2, ',', ' '))
@php($sectionTitle = match(request('flow')) { 'entree' => 'Gestion des entrées', 'sortie' => 'Gestion des sorties', default => 'Tableau de bord' })
@php($actionLabel = match(request('flow')) { 'entree' => 'Nouvelle entrée', 'sortie' => 'Nouvelle sortie', default => 'Nouvelle opération' })
@php($defaultType = match(request('flow')) { 'entree' => 'approvisionnement', 'sortie' => 'depense', default => request('type', 'approvisionnement') })
@php($availableTypes = match(request('flow')) { 'entree' => ['approvisionnement' => 'Approvisionnement'], 'sortie' => ['depense' => 'Dépense'], default => App\Models\Transaction::OPERATION_TYPES })
@include('partials.sidebar')
<div class="main-shell"><header class="topbar"><span>Mon espace <span class="muted mx-2">/</span> <strong>{{ $sectionTitle }}</strong></span><span class="top-date">{{ now()->translatedFormat('l d F Y') }}</span></header><main class="dashboard">
<div class="page-heading"><div><p class="eyebrow">{{ $isGlobalDashboard ? 'VUE GLOBALE DE L’ENTREPRISE' : 'MES INDICATEURS DE CAISSE' }}</p><h1>{{ $sectionTitle }}<span class="heading-dot">.</span></h1><p class="muted">{{ request('flow') === 'entree' ? 'Consultez les approvisionnements de la caisse.' : (request('flow') === 'sortie' ? 'Consultez les dépenses de la caisse.' : ($isGlobalDashboard ? 'Les indicateurs de tous les utilisateurs, en un coup d’œil.' : 'Vos indicateurs sont calculés à partir de vos propres opérations.')) }}</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#operationModal"><span class="me-2">＋</span> {{ $actionLabel }}</button></div>
@if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger" role="alert"><strong>L’opération n’a pas pu être effectuée.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="stat-grid"><article class="stat-card balance-card"><div class="stat-title">{{ $isGlobalDashboard ? 'Solde global' : 'Solde de mes opérations' }} <span>◈</span></div><div class="stat-value">{{ $money($balance) }} <small>{{ config('caisse.currency') }}</small></div><div class="stat-foot"><span class="status-dot"></span> {{ $isGlobalDashboard ? 'Toutes les opérations validées' : 'Calculé selon vos opérations validées' }}</div></article>
<article class="stat-card"><div class="stat-title">Total des entrées <span class="stat-icon in">↙</span></div><div class="stat-value">{{ $money($totals['recette'] + $totals['approvisionnement']) }} <small>{{ config('caisse.currency') }}</small></div><div class="stat-foot">Approvisionnements · sélection actuelle</div></article>
<article class="stat-card"><div class="stat-title">Total des sorties <span class="stat-icon out">↗</span></div><div class="stat-value">{{ $money($totals['depense'] + $totals['retrait']) }} <small>{{ config('caisse.currency') }}</small></div><div class="stat-foot">Dépenses · sélection actuelle</div></article>
<article class="stat-card"><div class="stat-title">Opérations du jour <span class="stat-icon neutral">⇄</span></div><div class="stat-value">{{ $todayCount }} <small>opérations</small></div><div class="stat-foot">Aujourd’hui · hors annulations</div></article></div>
<div class="chart-grid"><section class="panel"><div class="panel-heading"><div><h2>{{ $isGlobalDashboard ? 'Les flux de l’entreprise' : 'Les flux de mes opérations' }}</h2><p>Entrées et sorties, mouvements de fonds inclus</p></div><span class="period-tag">7 derniers jours</span></div><div class="chart-wrap"><canvas id="cashChart" role="img" aria-label="Flux de caisse sur les sept derniers jours"></canvas></div><details class="small muted"><summary>Données du graphique</summary><table class="table"><thead><tr><th>Jour</th><th>Entrées</th><th>Sorties</th></tr></thead><tbody>@foreach($chart as $day)<tr><td>{{ $day['label'] }}</td><td>{{ $money($day['in']*100) }}</td><td>{{ $money($day['out']*100) }}</td></tr>@endforeach</tbody></table></details></section>
<section class="panel overview"><p class="eyebrow">SUIVI DES FLUX</p><h2>Votre caisse en équilibre.</h2><p class="muted">Les approvisionnements et les dépenses sont suivis clairement.</p><div class="fund-row"><span class="fund-symbol in">＋</span><div>Approvisionnements<strong>{{ $money($totals['approvisionnement']) }} <small>{{ config('caisse.currency') }}</small></strong></div></div><div class="fund-row"><span class="fund-symbol out">−</span><div>Dépenses<strong>{{ $money($totals['depense']) }} <small>{{ config('caisse.currency') }}</small></strong></div></div><div class="overview-note">↳ Montants de la sélection actuelle</div></section></div>
<div class="analytics-grid">
<section class="panel analytics-card"><div class="panel-heading"><div><h2>Répartition des mouvements</h2><p>Montants cumulés par type d’opération</p></div></div><div class="chart-wrap compact"><canvas id="typeChart" role="img" aria-label="Répartition des montants par type de mouvement"></canvas></div></section>
<section class="panel analytics-card"><div class="panel-heading"><div><h2>Modes de paiement</h2><p>Répartition des flux selon le moyen utilisé</p></div></div><div class="chart-wrap compact"><canvas id="paymentChart" role="img" aria-label="Répartition des montants par mode de paiement"></canvas></div></section>
</div>
<section class="panel operations" id="operations"><div class="panel-heading"><div><h2>Historique commun des opérations <span class="count-tag">{{ $transactions->total() }}</span></h2><p>Tous les utilisateurs voient les opérations de l’entreprise et le nom de leur créateur.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary btn-sm" href="{{ route('reports.export', ['format'=>'pdf', ...request()->except('page')]) }}">↓ PDF</a><a class="btn btn-outline-secondary btn-sm" href="{{ route('reports.export', ['format'=>'xlsx', ...request()->except('page')]) }}">↓ Excel</a></div></div>
<form method="get" class="filters">@if(request('flow'))<input type="hidden" name="flow" value="{{ request('flow') }}">@endif<input class="form-control search-field" name="q" aria-label="Rechercher un motif" placeholder="Rechercher une opération…" value="{{ request('q') }}"><select class="form-select" name="type" aria-label="Type d’opération"><option value="">Tous les types</option>@foreach($availableTypes as $value=>$label)<option value="{{ $value }}" @selected(request('type')===$value)>{{ $label }}</option>@endforeach</select><select name="period" class="form-select" aria-label="Période"><option value="">Toutes les périodes</option>@foreach(['day'=>'Aujourd’hui','week'=>'Cette semaine','month'=>'Ce mois'] as $key=>$label)<option value="{{ $key }}" @selected(request('period')===$key)>{{ $label }}</option>@endforeach</select><select class="form-select" name="status" aria-label="Statut"><option value="">Tous les statuts</option><option value="active" @selected(request('status')==='active')>Validées</option><option value="cancelled" @selected(request('status')==='cancelled')>Annulées</option></select><button class="btn btn-filter">Filtrer</button><a class="reset-link" href="{{ route('dashboard', request('flow') ? ['flow' => request('flow')] : []) }}">Réinitialiser</a><div class="date-filters"><label>Du <input type="date" name="from" class="form-control" value="{{ request('from') }}"></label><label>Au <input type="date" name="to" class="form-control" value="{{ request('to') }}"></label></div></form>
<div class="table-responsive"><table class="table ledger-table"><thead><tr><th>Opération / motif</th><th>Date</th><th>Mode de paiement</th><th>Montant</th><th>Statut</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($transactions as $t)<tr><td><div class="operation-cell"><span class="operation-icon {{ $t->isInflow() ? 'in' : 'out' }}">{{ $t->isInflow() ? '↙' : '↗' }}</span><div><strong>{{ $t->description }}</strong><small>{{ $t->reference }} · {{ App\Models\Transaction::TYPES[$t->type] }} · Créée par {{ $t->user->name }}</small>@if($t->justification)<small>{{ $t->justification }}</small>@endif</div></div></td><td>{{ $t->occurred_on->format('d/m/Y') }}</td><td><span class="payment-dot"></span>{{ App\Models\Transaction::METHODS[$t->payment_method] }}</td><td class="amount {{ $t->isInflow() ? 'text-income' : '' }}">{{ $t->isInflow() ? '+' : '−' }} {{ $money($t->amount_minor) }}<small>{{ config('caisse.currency') }}</small></td><td><span class="badge-status {{ $t->cancelled_at ? 'cancelled' : '' }}">{{ $t->cancelled_at ? 'Annulée' : 'Validée' }}</span>@if($t->cancelled_at)<small class="d-block muted mt-1">{{ $t->cancellation_reason }}<br>{{ $t->canceller?->name }} · {{ $t->cancelled_at->format('d/m/Y H:i') }}</small>@endif</td><td class="text-end"><a class="btn btn-sm btn-light" href="{{ route('transactions.receipt',$t) }}" aria-label="Reçu {{ $t->reference }}">Reçu</a>@unless($t->cancelled_at)<button class="btn btn-sm cancel-button" data-bs-toggle="modal" data-bs-target="#cancelModal" data-action="{{ route('transactions.cancel',$t) }}" data-reference="{{ $t->reference }}">Annuler</button>@endunless</td></tr>@empty<tr><td colspan="6"><div class="empty-state"><span>↔</span><h3>Aucune opération pour le moment</h3><p>Enregistrez votre première opération ou ajustez les filtres.</p></div></td></tr>@endforelse</tbody></table></div><div class="pagination-wrap">{{ $transactions->links('pagination::bootstrap-5') }}</div></section><footer class="page-footer"><span>clair. <span class="muted">La sérénité, dans vos comptes.</span></span><span>{{ config('caisse.currency') }} · {{ config('app.timezone') }}</span></footer></main></div>
<div class="modal fade" id="operationModal" tabindex="-1" aria-labelledby="operationTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="post" action="{{ route('transactions.store') }}">@csrf<input type="hidden" name="request_key" value="{{ old('request_key', (string) Illuminate\Support\Str::uuid()) }}"><div class="modal-header"><h2 class="modal-title fs-5" id="operationTitle">{{ $actionLabel }}</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button></div><div class="modal-body"><div class="row g-3"><div class="col-6"><label class="form-label" for="type">Type</label><select class="form-select" id="type" name="type" required>@foreach($availableTypes as $value=>$label)<option value="{{ $value }}" @selected(old('type', $defaultType)===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-6"><label class="form-label" for="occurred_on">Date</label><input class="form-control" id="occurred_on" name="occurred_on" type="date" max="{{ today()->toDateString() }}" value="{{ old('occurred_on', today()->toDateString()) }}" required></div><div class="col-6"><label class="form-label" for="amount">Montant ({{ config('caisse.currency') }})</label><input class="form-control" type="number" id="amount" name="amount" min="0.01" max="9999999999.99" step="0.01" value="{{ old('amount') }}" required></div><div class="col-6"><label class="form-label" for="payment_method">Mode de paiement</label><select class="form-select" id="payment_method" name="payment_method" required>@foreach(App\Models\Transaction::METHODS as $value=>$label)<option value="{{ $value }}" @selected(old('payment_method')===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-12"><label class="form-label" for="description">Motif</label><input class="form-control" id="description" name="description" maxlength="255" value="{{ old('description') }}" placeholder="Ex. Achat de fournitures de bureau" required></div><div class="col-12"><label class="form-label" for="justification">Justificatif ou référence <span class="muted">(facultatif)</span></label><textarea class="form-control" id="justification" name="justification" maxlength="5000" rows="3" placeholder="N° de facture, bénéficiaire, détails…">{{ old('justification') }}</textarea></div></div><p class="small muted mt-3 mb-0">L’opération sera attribuée à {{ auth()->user()->name }}. Le solde sera mis à jour immédiatement.</p></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Fermer</button><button class="btn btn-primary">Enregistrer l’opération</button></div></form></div></div>
<div class="modal fade" id="cancelModal" tabindex="-1" aria-labelledby="cancelTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="post" id="cancelForm">@csrf<div class="modal-header"><h2 id="cancelTitle" class="modal-title fs-5">Annuler l’opération</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button></div><div class="modal-body"><p>L’opération restera dans l’historique. Son effet sur le solde sera inversé.</p><label for="cancellation_reason" class="form-label">Motif de l’annulation</label><textarea id="cancellation_reason" name="cancellation_reason" class="form-control" required minlength="5" maxlength="255"></textarea></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Conserver</button><button class="btn btn-danger">Confirmer l’annulation</button></div></form></div></div>
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.8/dist/chart.umd.min.js"></script><script>
const flows = @json($chart);
if (window.Chart) new Chart(document.getElementById('cashChart'), {type:'bar', data:{labels:flows.map(d=>d.label),datasets:[{label:'Entrées', data:flows.map(d=>d.in), backgroundColor:'#276553', borderRadius:5, maxBarThickness:22},{label:'Sorties',data:flows.map(d=>d.out),backgroundColor:'#d7a974',borderRadius:5,maxBarThickness:22}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',align:'start',labels:{usePointStyle:true,pointStyle:'circle',boxWidth:7,padding:22}}},scales:{x:{grid:{display:false},border:{display:false}},y:{beginAtZero:true,border:{display:false},grid:{color:'#eef0eb'},ticks:{maxTicksLimit:5}}}}});
const typeFlows = @json($typeChart);
const paymentFlows = @json($paymentChart);
const doughnutOptions = {responsive:true,maintainAspectRatio:false,cutout:'64%',plugins:{legend:{position:'right',labels:{usePointStyle:true,pointStyle:'circle',boxWidth:8,padding:18,font:{size:13}}},tooltip:{callbacks:{label:context=>`${context.label}: ${new Intl.NumberFormat('fr-FR').format(context.raw)} {{ config('caisse.currency') }}`}}}};
if (window.Chart) new Chart(document.getElementById('typeChart'), {type:'doughnut',data:{labels:typeFlows.map(d=>d.label),datasets:[{data:typeFlows.map(d=>d.value),backgroundColor:['#276553','#d7a974','#7cae91','#b26d5f'],borderWidth:0,hoverOffset:8}]},options:doughnutOptions});
if (window.Chart) new Chart(document.getElementById('paymentChart'), {type:'doughnut',data:{labels:paymentFlows.map(d=>d.label),datasets:[{data:paymentFlows.map(d=>d.value),backgroundColor:['#315f53','#d2a66d','#7184ad'],borderWidth:0,hoverOffset:8}]},options:doughnutOptions});
document.getElementById('cancelModal').addEventListener('show.bs.modal', event=>{ document.getElementById('cancelForm').action=event.relatedTarget.dataset.action; document.getElementById('cancelTitle').textContent='Annuler '+event.relatedTarget.dataset.reference; });
@if($errors->has('amount') || $errors->has('description') || $errors->has('occurred_on') || $errors->has('payment_method') || $errors->has('type') || $errors->has('justification'))
new bootstrap.Modal(document.getElementById('operationModal')).show();
@endif
</script>@endpush
