@extends('layout')
@section('title', 'Utilisateurs')
@section('content')
@include('partials.sidebar')
<div class="main-shell"><header class="topbar"><span>Administration <span class="muted mx-2">/</span> <strong>Utilisateurs</strong></span><span class="top-date">{{ now()->translatedFormat('l d F Y') }}</span></header><main class="dashboard"><div class="page-heading"><div><p class="eyebrow">GESTION DES ACCÈS</p><h1>Utilisateurs<span class="heading-dot">.</span></h1><p class="muted">Tous les comptes inscrits à la caisse de l’entreprise.</p></div><a class="btn btn-light" href="{{ route('dashboard') }}">← Retour au dashboard</a></div>
@if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
<div class="stat-grid admin-stats"><article class="stat-card"><div class="stat-title">Comptes inscrits</div><div class="stat-value">{{ $users->total() }}</div><div class="stat-foot">Utilisateurs et administrateur</div></article><article class="stat-card"><div class="stat-title">Comptes actifs</div><div class="stat-value">{{ App\Models\User::where('is_active', true)->count() }}</div><div class="stat-foot">Peuvent se connecter</div></article><article class="stat-card"><div class="stat-title">Comptes bloqués</div><div class="stat-value">{{ App\Models\User::where('is_active', false)->count() }}</div><div class="stat-foot">Accès suspendu</div></article></div>
<section class="panel operations"><div class="panel-heading"><div><h2>Comptes de l’entreprise</h2><p>Le blocage conserve le compte et toutes ses opérations.</p></div></div><div class="table-responsive"><table class="table ledger-table"><thead><tr><th>Utilisateur</th><th>Rôle</th><th>Inscription</th><th>Opérations créées</th><th>Statut</th><th class="text-end">Action</th></tr></thead><tbody>@foreach($users as $user)<tr><td><div class="operation-cell"><span class="avatar">{{ mb_substr($user->name,0,1) }}</span><div><strong>{{ $user->name }}</strong><small>{{ $user->email }}</small></div></div></td><td>{{ $user->is_admin ? 'Administrateur' : 'Utilisateur' }}</td><td>{{ $user->created_at->format('d/m/Y H:i') }}</td><td>{{ $user->transactions_count }}</td><td><span class="badge-status {{ $user->is_active ? '' : 'cancelled' }}">{{ $user->is_active ? 'Actif' : 'Bloqué' }}</span></td><td class="text-end">@if($user->is_admin)<span class="muted small">Compte principal</span>@else<form method="post" action="{{ route('admin.users.toggle-status', $user) }}" class="d-inline">@csrf @method('PATCH')<button class="btn btn-sm {{ $user->is_active ? 'btn-outline-danger' : 'btn-outline-success' }}">{{ $user->is_active ? 'Bloquer' : 'Débloquer' }}</button></form>@endif</td></tr>@endforeach</tbody></table></div><div class="pagination-wrap">{{ $users->links('pagination::bootstrap-5') }}</div></section><footer class="page-footer"><span>CaisseFlow <span class="muted">La sérénité, dans vos comptes.</span></span><span>Administration des accès</span></footer></main></div>
@endsection
